task_tracker/task_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

tasks_urlpatterns = [
    path('', views.index, name='tasks_index'),
    path('add/', views.TaskFormView.as_view(), name='add_task'),
    path('reassign_tasks/', views.reassign_tasks, name='reassign_tasks'),
    path('<int:task_id>/', views.detail, name='detail'),
]

urlpatterns = [
    path('admin/', admin.site.urls),    path('', views.index, name='tasks_index'),
    path('tasks/', include((tasks_urlpatterns, 'tasks'), namespace='tasks')),
]

task_tracker/task_tracker/models.py
import uuid
from django.db import models
from django.core.exceptions import ValidationError

from . import producer


class ExternalUser(models.Model):
    public_id = models.UUIDField(default=uuid.uuid4, editable=False)
    username = models.CharField(max_length=150, blank=True, editable=False)
    full_name = models.CharField(max_length=255, blank=True, editable=False)
    email = models.EmailField(max_length=255, blank=True, editable=False)
    role = models.CharField(max_length=32, blank=True, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.full_name


class Task(models.Model):
    STATUS_NEW = 'new'
    STATUS_ASSIGNED = 'assigned'
    STATUS_COMPLETED = 'completed'
    STATUS_CHOICES = (
        (STATUS_NEW, 'New'),
        (STATUS_ASSIGNED, 'Assigned'),
        (STATUS_COMPLETED, 'Completed'),
    )
    public_id = models.UUIDField(default=uuid.uuid4, editable=False)
    reporter = models.ForeignKey(ExternalUser, on_delete=models.CASCADE, related_name='tasks_reported')
    assignee = models.ForeignKey(ExternalUser, on_delete=models.CASCADE, related_name='tasks_assigned', null=True)
    title = models.CharField(max_length=255)
    jira_id = models.CharField(null=True, max_length=64)
    description = models.TextField()
    status = models.CharField(max_length=32, choices=STATUS_CHOICES, default=STATUS_NEW)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __init__(self, *args, **kwargs):
        super(Task, self).__init__(*args, **kwargs)
        self.__original_status = self.status

    def __str__(self):
        return f'#{self.id}: {self.status}'

    @classmethod
    def reassign_tasks(cls):
        queryset = cls.objects.filter(status__in=[cls.STATUS_ASSIGNED, cls.STATUS_NEW])
        for task in queryset:
            task.assignee = ExternalUser.objects.filter(role='developer').order_by('?').first()
            task.status = Task.STATUS_ASSIGNED
            task.save()

    def save(self, *args, **kwargs):
        if '[' in self.title or ']' in self.title:
            raise ValidationError('jira-id shouldn\'t be in title')
        if not self.id:
            event_data = {
                'public_id': str(self.public_id),
                'reporter': str(self.reporter.public_id),
                'assignee': str(self.assignee.public_id) if self.assignee else None,
                'description': self.description,
                'title': self.title,
                'jira_id': self.jira_id,
                'status': self.status
            }
            producer.publish('task_created', event_data)
        else:
            event_data = {
                'public_id': str(self.public_id),
                'reporter': str(self.reporter.public_id),
                'assignee': str(self.assignee.public_id) if self.assignee else None,
                'description': self.description,
                'title': self.title,
                'jira_id': self.jira_id,
                'status': self.status
            }
            producer.publish('task_updated', event_data)
        super(Task, self).save(*args, **kwargs)
        if self.status != self.__original_status:
            event_data = {
                'public_id': str(self.public_id),
                'new_status': self.status,
                'original_status': self.__original_status
            }
            producer.publish('task_status_changed', event_data)

    def delete(self, *args, **kwargs):
        super(Task, self).delete(*args, **kwargs)
        event_data = {
            'public_id': str(self.public_id)
        }
        producer.publish('task_deleted', event_data)

task_tracker/task_tracker/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}My amazing site{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/light.css">
</head>

<body>
    <div id="sidebar">
        {% block sidebar %}
        <div class="container">
            Current user
            <pre>
{{ current_oauth_user | pprint }}
            </pre>
        </div>
        {% endblock %}
    </div>

    <div id="content" class="container">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

task_tracker/task_tracker/templates/tasks/detail.html
{% extends "base.html" %}


{% block content %}
<div class="container">
    <a href="{% url 'tasks:tasks_index' %}">Back to Tasks List</a>
</div>
<div class="container">
    <h3>{{ task.public_id }} – {{ task.status }}</h3>
    <div class="container">
        <span class="label label-default">Reporter</span> {{ task.reporter }}
        <span class="label label-default">Assignee</span> {{ task.assignee }}
    </div>
    <p>
        {{ task.description }}
    </p>
</div>
{% endblock %}

task_tracker/task_tracker/templates/tasks/index.html
{% extends "base.html" %}

{% block content %}
<div class="">
    <h1>Tasks</h1>
    <menu>
        <a type="button" class="btn btn-primary" href="{% url 'tasks:add_task' %}">Add Task</a> <br/>
        <a type="button" class="btn btn-primary" href="{% url 'tasks:reassign_tasks' %}">(Re)Assign Tasks!</a>
    </menu>
    <ul>
        {% for task in tasks %}
            <li>
                <a href="{% url 'tasks:detail' task.id %}">
                    {{ task.public_id }} – {{ task.assignee.email }}
                </a>
            </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

task_tracker/task_tracker/templates/tasks/task_form.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
</div>

{% endblock %}